name: Daily Journal Update

on:
  schedule:
    - cron: '0 23 * * *'   # 06:00 WIB (GMT+7)
    - cron: '0 7 * * *'    # 14:00 WIB (GMT+7)
    - cron: '0 15 * * *'   # 22:00 WIB (GMT+7)
  workflow_dispatch:  # Bisa dijalankan manual

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Git user
        run: |
          git config --global user.name "FatihZee"
          git config --global user.email "viananto1234@gmail.com"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests
          pip install pytz  # Install pytz for timezone support

      - name: Run Journal Script
        env: 
          API_KEY: ${{ secrets.API_KEY }}  # Menyertakan API Key dari GitHub Secrets
        run: python daily_journal.py

      - name: Commit and Push Changes
        run: |
          git add progress.txt
          git add PROGRESS.md
          git commit -m "Daily Journal Update"
          git push origin main
